version: '3.5'

services:
  postgres:
    container_name: postgres_container2
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: test
    ports:
      - "5432:5432"